version: '3'

services:
  redis-0:
    image: redis:7.0.12-alpine
    hostname: redis-0
    container_name: redis-0
    command: redis-server /etc/redis/redis.conf
    volumes:
#      - ./redis-0-data:/data
      - ./config/redis0.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always

  redis-1:
    image: redis:7.0.12-alpine
    hostname: redis-1
    container_name: redis-1
    command: redis-server /etc/redis/redis.conf --slaveof redis-0 6379
    volumes:
#      - ./redis-1-data:/data
      - ./config/redis1.conf:/etc/redis/redis.conf
    ports:
      - 6380:6379
    restart: always
    depends_on:
      - redis-0

  redis-2:
    image: redis:7.0.12-alpine
    hostname: redis-2
    container_name: redis-2
    command: redis-server /etc/redis/redis.conf --slaveof redis-0 6379
    volumes:
#      - ./redis-2-data:/data
      - ./config/redis2.conf:/etc/redis/redis.conf
    ports:
      - 6381:6379
    restart: always
    depends_on:
      - redis-0

  redis-sentinel-0:
    image: redis:7.0.12-alpine
    container_name: redis-sentinel-0
    command: redis-server /etc/redis/sentinel0.conf --sentinel
    volumes:
      - ./config/sentinel:/etc/redis
    ports:
      - 26379:26379
    restart: always
    depends_on:
      - redis-0
      - redis-1
      - redis-2

  redis-sentinel-1:
    image: redis:7.0.12-alpine
    container_name: redis-sentinel-1
    command: redis-sentinel /etc/redis/sentinel1.conf --sentinel
    volumes:
      - ./config/sentinel:/etc/redis
    ports:
      - 26380:26379
    restart: always
    depends_on:
      - redis-0
      - redis-1
      - redis-2

  redis-sentinel-2:
    image: redis:7.0.12-alpine
    container_name: redis-sentinel-2
    command: redis-sentinel /etc/redis/sentinel2.conf --sentinel
    volumes:
      - ./config/sentinel:/etc/redis
    ports:
      - 26381:26379
    restart: always
    depends_on:
      - redis-0
      - redis-1
      - redis-2
